config/routes.rb
 Rails.application.routes.draw do

  devise_for :expresso_user, :registered_user, :ldap_users, skip: [ :sessions ]

  devise_scope :expresso_user do
    root to: "sessions#new", :as => 'expresso_user_root'
    get 'sign_in' => 'sessions#new', :as => :new_session_expresso_user
    match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    get '/auth/failure', to: 'sessions#omniauth_failure'
    get 'sign_out' => 'sessions#destroy'
  end

  devise_scope :ldap_user do
    root to: "sessions#new"
    delete 'sign_out' => 'sessions#destroy'
   end

  devise_scope :registered_user do
    root to: "sessions#new", :as => 'registered_user_root'
    get 'sign_in' => 'sessions#new', :as => :new_session
    post 'sign_in' => 'sessions#create', :as => :create_session
    delete 'sign_out' => 'sessions#destroy', :as => :destroy_session
  end

  get 'dashboard' => "dashboard#index"

  get 'widget/:token' => 'feedback_forms#code'

  get 'protected' => 'protected#index'

  get 'proxy' => 'proxy#index'

  resources  :feedback_targets do
    member do
     get 'search_for_members' => 'feedback_targets#search_for_members', as: 'members_for'
     post 'add_members' => 'feedback_targets#add_members', as: 'add_members_for'
     delete 'remove_member' => 'feedback_targets#remove_member', as: 'remove_member_for'
    end
    resources :feedbacks do

    end
    resources :feedback_forms do
      member do
        delete 'destroy_attribute' => 'feedback_forms#destroy_attribute'
        get 'new_attribute' => 'feedback_forms#new_attribute'
      end
      resources :feedbacks do
        member do
          delete 'destroy_comment' => 'feedbacks#destroy_comment'
          post 'add_comment' => 'feedbacks#add_comment'
          post 'archive' => 'feedbacks#archive'
          post 'unarchive' => 'feedbacks#unarchive'
          get 'comments' => 'feedbacks#comments'
          put 'fire_event'=> 'feedbacks#fire_event'
          get 'show_detail'=> 'feedbacks#show_detail'
        end
      end
    end
  end

  get '/users/autocomplete', to: 'users#autocomplete', as: 'autocomplete_user'

  get '/user_applications', to: redirect('/feedback_targets')
  get '/user_applications/:feedback_target_id', to: redirect  { |path_params, req| "/feedback_targets/#{path_params[:feedback_target_id]}" }

  mount FeedbackServerAPI => '/api/'

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ProtectedController
  respond_to :html, :json, :js

  before_filter :define_breadcrumbs_index , :only => [:index]

  def index
    @feedback_form = @feedback_target.feedback_forms.find(params[:feedback_form_id])
    authorize!(:list_feedbacks, @feedback_form) do
      @feedbacks = list_feedbacks

      respond_to do |format|
        format.html { render :index }
        format.json { render json: FeedbacksDatatable.new(view_context) }
        format.js { render 'index.js.erb' }
      end
    end
  end

  def update
    @feedback = feedback_from_params

    @feedback.update_attributes(feedback_params)

    respond_to do |format|
      format.html { redirect_to @feeback }
      format.js { render partial: 'detail_column', locals: { feedback: @feedback} }
    end
  end

  def fire_event
    @feedback = feedback_from_params
    error = nil
    event = params[:event]
    begin
      unless @feedback.state_machine.fire_state_event(params[:event])
        @error = 'invalid_transition'
      end
    rescue Exception => e
      @error = "error_on_state_machine_evet"
    end
    respond_to do |format|
      format.json do
        if @error
          result = respond_error_json({ message: I18n.t(@error, event), object:  @feedback})
        else
          result = respond_success_json({ message: @error, object:  @feedback})
        end
        render :json =>  result
      end
      format.js {}
    end
  end

  def comments
    begin
      @feedback = feedback_from_params
      @comments = @feedback.comments
      respond_to do |format|
        format.js {}
        format.html { render :partial => 'feedbacks/comments_list', :locals => { feedback: @feedback} }
        format.json { render :json =>  respond_success_json(:object => @comments) }
      end
    rescue Exception => ex
      respond_to do |format|
        format.html { render :partial => :comments_list, :locals => { feedback: @feedback} }
      end
    end
  end

  def add_comment
    @feedback = feedback_from_params
    @comment = @feedback.comments.create(:user => current_user, :text => params[:comment][:text])
    respond_to do |format|
      format.html { redirect_to action: :index }
      format.json do
        begin
          @feedback.save!
          render :json => respond_success_json(:object => @comment)
        rescue Exception => e
          render json: respond_error_json(:message => e.message ,:object => @feedback), :content_type => 'application/javascript'
        end
      end
      format.js do
        begin
          @feedback.save!
          @comment = Comment.new
          render :comments
        rescue Exception => e
          @error_message = e.message
          @controller_action = "feedbacks##{action_name}"
          render :comment_error
        end
      end
    end
  end

  def destroy_comment
    begin
      @feedback = feedback_from_params
      @comment = @feedback.comments.find(params[:comment_id])
      @comment.destroy
      @comment = Comment.new
      respond_to do |format|
        format.html { redirect_to action: :index }
        format.json { render :json => respond_success_json(:object => @comment) }
        format.js   { render :comments }
      end
    rescue Exception => e
      respond_to do |format|
        format.html { redirect_to :index}
        format.json { render json: respond_error_json(:message => e.message ,:object => @feedback), :content_type => 'application/javascript'}
        format.js   { render :comments }
      end
    end
  end

  def show_detail
    @feedback = feedback_from_params
    respond_to do |format|
      format.js {}
      format.html { render partial: 'detail_panel', :locals => { feedback: @feedback } }
    end
  end

  def destroy
    @feedback = nil
    @scope = 'archived'

    @feedback = feedback_from_params

    authorize!(:destroy_feedback, @feedback) do
      respond_to do |format|
        format.html do
          @feedback.destroy
          redirect_to action: :index
        end
        format.js do
          begin
            @feedback.destroy!
            list_and_authorize_feedbacks do |feedbacks|
              @feedbacks = feedbacks
              render :action => :index
            end
          rescue Exception => e
            render json: respond_error_json(:message => e.message ,:object => @feedback), :content_type => 'application/javascript'
          end
        end
      end
    end
  end

  def archive
    @feedback = nil
    @scope = 'default'

    @feedback = feedback_from_params
    @feedback.archive!
    respond_to do |format|
      format.html do
        redirect_to action: :index
      end
      format.js do
        begin
          redirect_to feedback_target_feedback_form_feedbacks_path(@feedback_target, @feedback.feedback_form, view_context.pagination_params)
        rescue Exception => e
          render json: respond_error_json(:message => e.message ,:object => @feedback), :content_type => 'application/javascript'
        end
      end
    end
  end

  def unarchive
    @feedback = nil
    @scope = 'archived'

    @feedback = feedback_from_params
    @feedback.unarchive!

    respond_to do |format|
      format.html { redirect_to action: :index }
      format.js do
        redirect_to feedback_target_feedback_form_feedbacks_path(@feedback_target, @feedback.feedback_form, view_context.pagination_params.merge(:scope => 'archived'))
      end
    end
  end

protected

  def feedback_params
    params.require(:feedback).permit :assignee_attributes => [:id]
  end

  def list_feedbacks

    # @feedback_target = current_user.my_targets.find(params[:feedback_target_id])
    #
    # if params[:feedback_form_id]
    #   @feedback_form = @feedback_target.feedback_forms.find(params[:feedback_form_id])
    # else
    #   @feedback_form = nil
    # end
    #
    #
     @page = params[:page] || 1
    #
     @per_page = params[:per_page] || Feedback.per_page
    #
    # @scope = params['scope'] || 'default'
    #
    # feedbacks = []
    #
    # if @feedback_form
    #   feedbacks_relation = @feedback_form.feedbacks
    # else
    #   feedbacks_relation = @feedback_target.feedbacks
    # end

    feedbacks = FeedbacksFinder.new.execute(current_user, params).paginate(page: 1, per_page: @per_page)

    # if 'default'.eql? @scope
    #   feedbacks = feedbacks_relation.order(server_date_time: 'DESC').paginate(page: @page, per_page: @per_page)
    #   if feedbacks.empty?
    #     feedbacks = feedbacks_relation.order(server_date_time: 'DESC').paginate(page: 1, per_page: @per_page)
    #   end
    # elsif 'archived'.eql? @scope
    #   feedbacks = feedbacks_relation.archived.order(server_date_time: 'DESC').paginate(page: @page, per_page: @per_page)
    #   if feedbacks.empty?
    #     feedbacks = feedbacks_relation.archived.order(server_date_time: 'DESC').paginate(page: 1, per_page: @per_page)
    #   end
    # end

    feedbacks

  end
  def feedback_from_params
    if 'archived'.eql? @scope
      @feedback ||= feedback_target.feedbacks.archived.find params[:id]
    else
      @feedback ||= feedback_target.feedbacks.find params[:id]
    end
  end
  def feedback_target
    @feedback_target ||= FeedbackTarget.all_targets_for_user(current_user).find(feedback_target_id_param)
  end

  def feedback_target_id_param
    params[:feedback_target_id]
  end

  private
    def list_and_authorize_feedbacks
      @feedback_form = @feedback_target.feedback_forms.find(params[:feedback_form_id])
      authorize!(:list_feedbacks, @feedback_form) do
        yield list_feedbacks
      end
    end

    def define_breadcrumbs_index
      add_breadcrumb  feedback_target.name, feedback_target
      @feedback_form = @feedback_target.feedback_forms.find(params[:feedback_form_id])
      add_breadcrumb  @feedback_form.name,feedback_target_feedback_form_path(@feedback_target, @feedback_form)
      add_breadcrumb  'Feedbacks'
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper

  def all_columns_for feedback
    columns = feedback.columns.collect {|c| c[:key] }
    columns.delete 'comments'
    columns
  end

  def all_columns_for_collection(collection)
    arr_column_names = collection.map do |f|
        f.columns.collect {|c| c[:key] }
    end
    result = arr_column_names.flatten!
    return [] if result.nil?
    result = result.uniq.nil? ? result : result.uniq
    result.delete 'comments'
    result
  end

  def show_column_value(feedback, column_name)
begin
    value =  feedback.read_attribute(column_name)
    return raw '&nbsp;' if (value.is_a?(String) and value.empty?) or value.nil?
    #puts "Tipo: #{value.class.name} - value: #{value}"
    if 'screenshot_path'.eql?(column_name)
      #tag 'img', :src => "/" + url_for(value), :width => 150, height: 80
      return link_to(
            raw(content_tag(:span, pad(translate('Screenshot')), :class => 'fa fa-camera')),
            url_for( "/" + value),
            :class => 'screenshot_link')
    elsif value.is_a? Time
      return l value.in_time_zone, :format => '%d/%m/%y %H:%M'
    else
      result = value.to_s.scrub!
    end
rescue Exception => e
  puts feedback.inspect   
  "ERROR: #{e.message}"
end
  end

  def feedback_url(feedback)
    feedback_target_feedback_form_feedback_path(feedback.feedback_target, feedback.feedback_form, feedback)
  end

  def fire_event_url(feedback, state_transition)
    fire_event_feedback_target_feedback_form_feedback_path(
      feedback.feedback_target,
      feedback.feedback_form,
      feedback, event: state_transition.event)
  end

  def link_to_feedback_transition(feedback ,state_transition, link_to_options={})
    link_text = state_transition.event.to_s.humanize
    url = fire_event_url(feedback,state_transition)
    options = { data: { remote: true, method: 'put', event: state_transition.event, feedback: feedback.id } }
    link_to(link_text, url, link_to_options.merge(options))
  end


  def humanize_column(column_name)
    return "" if column_name.nil?
    if column_name.is_a?(String)
      return column_name.humanize
    else
      return column_name.to_s
    end
  end

  def pagination_params
    pagination_hash = {}
    if(params[:per_page])
      pagination_hash[:per_page] = params[:per_page]
    end
    if(params[:page])
      pagination_hash[:page] = params[:page]
    end
    pagination_hash
  end

  def link_to_archive feedback
    if current_user_can?(:archive_feedback, feedback)
      link_to(
        archive_feedback_target_feedback_form_feedback_path(@feedback_target, feedback.feedback_form,feedback, pagination_params),
        :method=> 'POST', :remote => true, :data => {:confirm => t('feedback.archive_confirmation_question'),
        :type => 'script', :target_selector => 'a'}
        ) do
            raw("<i class='fa fa-archive-o'></i>") +
            content_tag(:span, pad(t('Archive')))
        end
    end
  end

  def link_to_unarchive feedback
    if current_user_can?(:unarchive_feedback, feedback)
      link_to(
        unarchive_feedback_target_feedback_form_feedback_path(@feedback_target, feedback.feedback_form,feedback, pagination_params),
        :method=> 'POST', :remote => true, :data => {:confirm => t('feedback.unarchive_confirmation_question'),
        :type => 'script', :target_selector => 'a'}
        ) do
          content_tag(:span, pad(t('Unarchive')), :class => 'fa fa-undo')
        end
    end
  end

  def link_to_destroy feedback
    if current_user_can?(:destroy_feedback, feedback)
      link_to(
        feedback_target_feedback_form_feedback_path(@feedback_target, feedback.feedback_form,feedback, pagination_params),
        :method=> 'DELETE', :remote => true, :data => {:confirm => t('feedback.destroy_confirmation_question'),
        :type => 'script', :target_selector => 'a'}
        ) do
          content_tag(:span, pad(t('Destroy')), :class => 'fa fa-trash-o')
        end
    end
  end

  def show_detail_path feedback
    ft = feedback.feedback_target
    ff = feedback.feedback_form
    show_detail_feedback_target_feedback_form_feedback_path(ft, ff, feedback)
  end

  def id_for_panel_feedback_detail feedback
    "td_feedback_detail_#{feedback.id}"
  end

  def id_for_line_feedback_detail feedback
    "tr_feedback_detail_#{feedback.id}"
  end

  def feedback_detail_anchor feedback
    "feedback_detail_#{feedback.id}"
  end

  def state_filtered? state_name
    if params[:state].present?
      params[:state].include?(state_name.to_s)
    else
      return false
    end
  end

  def state_filtered_value(state_name)
    state_filtered?(state_name) ? 1 : 0
  end
end

app/views/feedbacks/_comment_form.html.erb
<%= bootstrap_form_for :comment,
  :url => add_comment_feedback_target_feedback_form_feedback_path(@feedback_target, feedback.feedback_form, feedback),
  :remote => true, :format => 'js',
  :html => {:class => 'comment_form'} do |f| %>
<div class="input-group">
  <%= f.text_area :text, :class=>"form-control custom-control", :required => true, :placeholder =>  t('feedback.comment.placeholder'), hide_label: true %>
  <span class="submit input-group-addon btn">
      <%= link_to  t('feedback.comment.send'), 'javascript:;' %>
  </span>
</div>
<% end %>

app/views/feedbacks/_comment_panel.html.erb
<div class="comment-panel panel panel-default" >
  <div class="panel-heading">
      <span class="panel-title"><i class='fa fa-comments fa-fw'></i><%= t('Comments') %></span>
  </div>
  <div class="panel-body">
    <%= render :partial => 'comments_list', :locals => {:feedback => feedback } %>
  </div>
  <div class="panel-footer">
    <%= render :partial => 'comment_form', :locals => {:feedback => feedback } %>
  </div>
</div>

app/views/feedbacks/_comments_list.html.erb
<ul class="comments_list">
  <% feedback.comments.all.sort(:created_at => -1).each_with_index do |comment, i| %>
    <% if i == 0 || i %2 ==0 %>
      <%= render partial: 'left_comment', :locals => {:comment => comment, :feedback => feedback} %>
    <% else %>
      <%= render partial: 'right_comment', :locals => {:comment => comment, :feedback => feedback}  %>
    <% end %>
  <% end %>
</ul>

app/views/feedbacks/_detail_column.html.erb
<%= bootstrap_form_for feedback, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8", url: feedback_url(feedback), remote: true,  method: 'put' do |f|  %>
  <% feedback.feedback_form.detail_checked_columns.each do |column| %>
    <label class="col-sm-4 control-label"><%= column.display_label %></label>
    <div class="col-sm-8">
      <div class="form-control-static">
        <%= show_column_value(feedback, column.name) %>
      </div>
    </div>
    <% if column.name.eql?(feedback.feedback_form.state_field)  %>
      <div class="col-sm-4"></div>
      <div class="col-sm-8">
      <%= render partial: 'workflow_actions', locals: {feedback: feedback} %>
      </div>
      <div class='clearfix'></div>
      <hr /  >
    <% end %>
  <% end %>
  <%= render partial: 'feedback_assignee', locals: { f: f, feedback: feedback } %>
<% end %>

app/views/feedbacks/_left_comment.html.erb
<li class="left clearfix">
  <span class="chat-img pull-left">
    <% if comment.user %>
      <img src="/images/50x50_blue.gif" alt="<%= comment.user.name  %>" class="img-circle">
    <% end %>
  </span>
  <div class="chat-body clearfix">
      <div class="header">
          <strong class="primary-font"><%= comment.user.name if comment.user %></strong>
          <small class="pull-right text-muted">
              <i class="fa fa-clock-o fa-fw"></i> <%= time_ago_in_words comment.created_at %>
              <%= if current_user_can?(:destroy_comment, comment)
                link_to   destroy_comment_feedback_target_feedback_form_feedback_path(feedback.feedback_form.feedback_target, feedback.feedback_form, feedback, :comment_id => comment.id),
                :method => 'delete',
                :data => {:confirm => t('feedback.comment.destroy_confirm'),:remote => true, 'original-title' => t('feedback.comment.remove_tooltip'), :toggle =>"tooltip", :placement => "top"} do %>
                  <i class="fa fa-minus fa-fw" alt='<%= t('feedback.comment.remove') %>'></i>
              <%
                end
              end %>
          </small>
      </div>
      <pre><%= comment.text %></pre>
  </div>
</li>

app/views/feedbacks/_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
      <h3 class="panel-title"><%= t('Recents Feedbacks') %></h3>
  </div>
  <div class="panel-body">
    <% if @last_feedbacks.empty? %>

      <p> <%= translate("No feedbacks registered yet") %></p>

    <% else  %>

      <div class="table-responsive">
          <table class="table table-bordered table-hover table-striped">
              <thead>
                  <tr>
                    <th><%= translate('When') %>?</th>
                    <th><%= translate('Application') %></th>
                    <th><%= translate('Description') %></th>
                  </tr>
              </thead>
              <tbody>
                 <% @last_feedbacks.each do  |feedback| %>
                    <tr>
                      <td><%= time_ago_in_words feedback.created_at if feedback.created_at%></td>
                      <td><%= feedback.feedback_target.name %></td>
                      <td><%= feedback.description %></td>
                    </tr>
                 <% end %>
              </tbody>
          </table>
      </div>
      <% end %>
      <div class="text-right">
          <%= link_to translate('All_male'), feedback_targets_path%>
      </div>
  </div>
</div>

app/views/feedbacks/_right_comment.html.erb
<li class="right clearfix">
  <span class="chat-img pull-right">
    <% if comment.user %>
      <img src="/images/50x50_red.gif" alt="<%= comment.user.name %>" class="img-circle">
    <% end %>
  </span>
  <div class="chat-body clearfix">
      <div class="header">
          <strong class="primary-font pull-right"><%= comment.user.name %></strong>
          <small class="text-muted">
              <i class="fa fa-clock-o fa-fw"></i> <%= time_ago_in_words comment.created_at %>
              <%= if  current_user_can?(:destroy_comment, comment)
                link_to  destroy_comment_feedback_target_feedback_form_feedback_path(feedback.feedback_form.feedback_target, feedback.feedback_form, feedback, :comment_id => comment.id),
                  :method => 'delete',
                  :data => {:confirm => t('feedback.comment.destroy_confirm'),:remote => true, 'original-title' => t('feedback.comment.remove_tooltip'), :toggle =>"tooltip", :placement => "top"} do %>
                  <i class="fa fa-minus fa-fw" alt='<%= t('feedback.comment.remove') %>'></i>
              <% end
              end %>
          </small>
      </div>
      <pre><%= comment.text %></pre>
  </div>
</li>

app/views/feedbacks/_table.html.erb
<%# if 'archived'.eql? @scope %>
<%#= link_to t('feedback.show_active_feedbacks'), url_for(feedback_target_feedback_form_feedbacks_path(@feedback_target, @feedback_form,pagination_params)), :class=>'scope_action', :data => {:remote => true, :updatable_element_selector => '#feedbacks_table'} %>
<%# else %>
<%#= link_to t('feedback.show_archived_feedbacks'), url_for(feedback_target_feedback_form_feedbacks_path(@feedback_target, @feedback_form,pagination_params.merge(:scope => 'archived'))), :class=>'scope_action', :data => {:remote => true, :updatable_element_selector => '#feedbacks_table'} %>
<%# end %>
<p class="pull-right">Listados dos mais recentes para os mais antigos</p>
<%#= will_paginate @feedbacks, :class => 'apple_pagination' %>
<table id="feedbacks" class="table table-bordered table-hover table-responsive table-striped" data-source="<%= feedback_target_feedbacks_url(:id=> params[:id], format: "json") %>">
  <thead>
    <tr>
        <td colspan="100">
          <%= will_paginate @feedbacks, :class => 'apple_pagination' %>
        </td>
    </tr>
    <tr>
      <!-- <th>Id</th>
      <th>Tipo Relato</th>
      <th>Data</th>
      <th>Texto</th>
      <th>Captura de Tela</th> -->
      <% @feedback_form.grid_checked_columns.each do |column| %>
        <%= content_tag :th, humanize_column(column.display_label) unless column.display_label.empty? %>
      <% end %>
      <th><%= t 'Actions' %></th>
    </tr>
  </thead>
  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr class='feedback_line' data-target-selector='#<%= id_for_panel_feedback_detail(feedback) %>'>
        <% grid_columns = @feedback_form.grid_columns || @feedback_form.all_columns %>
        <% grid_columns.each do |column_name| %>
          <% unless column_name.empty? %>
          <td><%= show_column_value(feedback, column_name) %></td>
          <% end %>
        <% end %>
        <td><%#= link_to t('Archive'), archive_feedback_target_feedback_path( @feedback_target, feedback), :remote => true, :method => :post, :data => {:type => 'json', :target_selector => 'a'} %>
          <% if feedback.active %>
            <%= link_to_archive(feedback)  %>
          <% else %>
            <%= link_to_unarchive(feedback) %>
            <%= link_to_destroy(feedback) %>
          <% end %>
          <%#= content_tag :a, t('Details'), :class => 'feedback_detail_link', :data => {:target_selector => "#feedback_detail_#{feedback.id }" } %>
          <%= link_to '', show_detail_path(feedback), class: 'detail_link', remote: true %>
        </td>
      </tr>
      <%= content_tag :tr, :id => id_for_line_feedback_detail(feedback), :class => 'feedback_detail' do %>
        <%= content_tag :td, {id: id_for_panel_feedback_detail(feedback), colspan: 100} do %>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
  <tfooter>
  <tr>
      <td colspan="100">
        <%= will_paginate @feedbacks, :class => 'apple_pagination' %>
      </td>
  </tr>
  </tfooter>
</table>
<script type='text/javascript'>
$('#feedbacks_table a[data-remote].scope_action').on('click', function(){
  var element_selector = $(this).data('updatableElementSelector');

  $(element_selector).hide();
})
</script>

app/views/feedbacks/_workflow_actions.html.erb
    <% if feedback.state_machine.state_transitions.count > 1 %>
        <button type='button' class='btn btn-sm btn-success' data-toggle="dropdown"> <span class="caret"></span>
          <%= I18n.t('Actions') %>
        </button>
        <ul class="dropdown-menu" role="menu">
        <% feedback.state_machine.state_transitions.each do |state_transition| %>
          <li><%= link_to_feedback_transition(feedback, state_transition) %></li>
        <% end %>
        </ul>
    <% elsif feedback.state_machine.state_transitions.count == 1 %>
      <%= link_to_feedback_transition(feedback, feedback.state_machine.state_transitions[0], class: 'btn btn-sm btn-success' ) %>
    <% end %>

app/views/feedbacks/fire_event.js.erb
var selector = '#<%= "#{id_for_panel_feedback_detail(@feedback)} .detail_column" %>';
$(selector).fadeOut(200 , function(){
  $(selector).html("<%= escape_javascript (render partial: 'detail_column', :locals => {:feedback => @feedback}) %>");
  $(selector).fadeIn(350);
});

app/views/feedbacks/index.html.erb
<h1 class="page-header"><%= @feedback_target.name %></h1>
<div class="panel panel-default">
  <div class="panel-heading">
      <h3 class="panel-title">Feedbacks</h3>
  </div>
  <div class="panel-body">
      <div id='feedbacks_filter'>
      <div class="btn-toolbar">
        <div class="btn-group" data-toggle="buttons">
          <label class="btn btn-primary btn-sm <%= ('1'.eql?(params[:assigned_to_me])) ? 'active' : '' %>"><input type="checkbox" name="options" id="option8">
          <%= t('feedback.assigned_to_me') %>
          <div class='hidden'>
           <% if '1'.eql?(params[:assigned_to_me]) %>
             <%= link_to t('feedback.assigned_to_me'), page_filter_path(assigned_to_me: '')%>
           <% else %>
           <%= link_to t('feedback.assigned_to_me'), page_filter_path(assigned_to_me: '1')%>
           <% end %>
          </div>
          </label>
        </div>
       <div class="btn-group" data-toggle="buttons">
         <% @feedback_form.all_machine_states_names.each do | state_name |%>
            <label class="btn btn-default btn-sm <%= state_filtered?(state_name.to_s) ? 'active' : '' %>">
              <input type="checkbox" name="options" value="<%= state_filtered_value(state_name) %>" id="option5">
              <%= state_name.to_s.humanize %>
              <div class="hidden">
              <%
              if params[:state] and params[:state].include? state_name.to_s %>
                <%= link_to page_filter_path(state: '')do %>
                  <%= state_name.to_s.humanize %>
                <% end %>
              <% else %>
                <%= link_to page_filter_path(state: state_name.to_s)do %>
                  <%= state_name.to_s.humanize %>
                <% end %>
              <% end %>
              </div>
            </label>
         <% end %>
       </div>
       <div class="btn-group" data-toggle="buttons">
         <label class="btn btn-warning btn-sm <%= ( params[:scope] and params[:scope].include? 'archived') ? 'active' : '' %>"><input type="checkbox" name="options" id="option8">
           <%= t('feedback.archived') %>
         <div class='hidden'>
          <% if params[:scope] and params[:scope].include? 'archived' %>
            <%= link_to t('feedback.archived'), page_filter_path(scope: '')%>
          <% else %>
          <%= link_to t('feedback.archived'), page_filter_path(scope: 'archived')%>
          <% end %>
         </div>
         </label>
       </div>
      </div>

      </div>
      <div id="feedbacks_table">
        <%= render :partial => 'table' %>
      </div>

  </div>
</div>

<% content_for :body_end do %>
  <%= javascript_include_tag 'feedbacks' %>

  <script type='text/javascript'>
  jQuery(document).on('ready page:load', function(e){
    jQuery('div.btn-toolbar').on('click.bs.button.data-api', 'label.btn', function(){
      var url = $(this).find('a')[0].href;
      Turbolinks.visit(url);
    });
  });
  </script>
<% end %>

app/views/feedbacks/index.js.erb
$('#feedbacks_table').slideUp(200 , function(){
  $('#feedbacks_table').html("<%= escape_javascript (render partial: 'table') %>");
  $('#feedbacks_table').slideDown(350);
});

app/views/feedbacks/new_assignee.js.erb
$('#assignee_content').slideUp(200 , function(){
  $('#assignee_content').html("<%= escape_javascript (render partial: 'feedback_assignee', locals: {feedback: @feedback}) %>");
  $('#assignee_content').slideDown(350);
});

app/views/feedbacks/show_detail.js.erb
<%
partial_html = escape_javascript (render partial: 'detail_panel', locals: {feedback: @feedback})
id_element = '#' + "#{id_for_panel_feedback_detail(@feedback)}"
id_row = '#' + "#{id_for_line_feedback_detail(@feedback)}"
%>
id_element = '<%= id_element %>';
id_row = '<%= id_row %>';
$(id_element).html("<%= partial_html %>");
$(id_row).fadeIn(350);
window.location = '#<%= feedback_detail_anchor(@feedback) %>';