config/routes.rb
 Rails.application.routes.draw do

  devise_for :expresso_user, :registered_user, :ldap_users, skip: [ :sessions ]

  devise_scope :expresso_user do
    root to: "sessions#new", :as => 'expresso_user_root'
    get 'sign_in' => 'sessions#new', :as => :new_session_expresso_user
    match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    get '/auth/failure', to: 'sessions#omniauth_failure'
    get 'sign_out' => 'sessions#destroy'
  end

  devise_scope :ldap_user do
    root to: "sessions#new"
    delete 'sign_out' => 'sessions#destroy'
   end

  devise_scope :registered_user do
    root to: "sessions#new", :as => 'registered_user_root'
    get 'sign_in' => 'sessions#new', :as => :new_session
    post 'sign_in' => 'sessions#create', :as => :create_session
    delete 'sign_out' => 'sessions#destroy', :as => :destroy_session
  end

  get 'dashboard' => "dashboard#index"

  get 'widget/:token' => 'feedback_forms#code'

  get 'protected' => 'protected#index'

  get 'proxy' => 'proxy#index'

  resources  :feedback_targets do
    member do
     get 'search_for_members' => 'feedback_targets#search_for_members', as: 'members_for'
     post 'add_members' => 'feedback_targets#add_members', as: 'add_members_for'
     delete 'remove_member' => 'feedback_targets#remove_member', as: 'remove_member_for'
    end
    resources :feedbacks do

    end
    resources :feedback_forms do
      member do
        delete 'destroy_attribute' => 'feedback_forms#destroy_attribute'
        get 'new_attribute' => 'feedback_forms#new_attribute'
      end
      resources :feedbacks do
        member do
          delete 'destroy_comment' => 'feedbacks#destroy_comment'
          post 'add_comment' => 'feedbacks#add_comment'
          post 'archive' => 'feedbacks#archive'
          post 'unarchive' => 'feedbacks#unarchive'
          get 'comments' => 'feedbacks#comments'
          put 'fire_event'=> 'feedbacks#fire_event'
          get 'show_detail'=> 'feedbacks#show_detail'
        end
      end
    end
  end

  get '/users/autocomplete', to: 'users#autocomplete', as: 'autocomplete_user'

  get '/user_applications', to: redirect('/feedback_targets')
  get '/user_applications/:feedback_target_id', to: redirect  { |path_params, req| "/feedback_targets/#{path_params[:feedback_target_id]}" }

  mount FeedbackServerAPI => '/api/'

end

app/models/feedback_target.rb
class FeedbackTarget
  include Mongoid::Document
  include Mongoid::Slug

  # Mongoid Paranoia adds soft delete to model
  # - destroy will set deleted_at to current_time
  # - models with deleted_at defined will be ignored on default scope
  # - deleted scope is added to allow list deleted instances
  include Mongoid::Paranoia

  include Tokenable

  # callbacks
  after_create :create_default_form!

  # fields
  field :name, type: String

  field :default_feedback_form_id, type: String

  # slug definition
  slug :name, history: true, scope: :owner

  # validations
  validates :name, uniqueness: { :case_sensitive => false, conditions: -> { where(deleted_at: nil) } }
  validates_presence_of :owner
  validates_presence_of :name

  # associations
  belongs_to :owner, class_name: 'User', inverse_of: :feedback_targets,
    foreign_key: 'owner_id', index: true
  has_and_belongs_to_many :members, class_name: 'User', inverse_of: :memberships, index: true
  has_many :feedback_forms,
            class_name: 'FeedbackForm',
            inverse_of: :feedback_target,
            foreign_key: 'feedback_target_id',
            dependent: :destroy

  has_many :feedbacks #, dependent: :destroy
  #belongs_to :default_feedback_form, class_name: 'FeedbackForm'
  #has_many :members, :class_name => 'User'

  # scopes
  scope :all_targets_for_user, ->(user){
      any_of({:owner => user}, {:member_ids.in => [user.id]})
  }

  def include_members member_ids_str
    return if member_ids_str.empty?
    arr_ids = member_ids_str.split(',')
    arr_ids.each do |id|
      if self.members.where(id: id).empty?
        self.members << User.find(id)
      end
    end
  end

  def remove_member member_id_str
    return false if member_id_str.empty?
    user = self.members.where(id: member_id_str).first
    return false if user.nil? #false se não encontrou membro
    return self.members.delete(user).present? #true se o usuario foi removido como membro
  end

  def members_usernames
    members_names = members.empty? ? []  : members.map {|m| m.username}
  end

  def list_members_candidates(username_filter)
    already_members_filter = members_usernames + [owner.username]
    User.by_username_or_email(username_filter) & User.where(:username.nin => already_members_filter)
  end

  def default_feedback_form
    self.feedback_forms.where(_id: self.default_feedback_form_id).first
  end

  def set_default_form! feedback_form
    self.write_attribute(:default_feedback_form_id, feedback_form.id.to_s)
    self.save!
  end

  def users
    @users ||= members.all + [owner]
  end

protected
  def create_default_form!
    form = nil
    begin
      #raise Exception.new "ABBBB"
      #creates a form using FeedbackFormTemplate.default_template as base
      form_attributes = FeedbackFormTemplate.default_template.attributes_template

      form_attributes.merge!(:feedback_target => self)

      form = FeedbackForm.create!(form_attributes)

      #set as default form for this feedback_target
      set_default_form! form
      save!
    rescue Exception => e
      destroy
      msg = e.message
      msg = "#{msg} #{form.errors}" if form
      raise "Error creating default form for application #{msg}"
    end
  end

end

app/controllers/feedback_targets_controller.rb
#encoding: UTF-8
class FeedbackTargetsController < ProtectedController
  before_filter :define_breadcrumbs, :only => [:show]
  #helper_method :render_code, :render_js_include

  def index
    @feedback_targets = FeedbackTarget.all_targets_for_user(current_user)
  end

  def new
    @feedback_target = current_user.feedback_targets.new
  end

  def show
    @feedback_target = feedback_target
  end

  def edit
    @feedback_target = FeedbackTarget.find(params[:id])
    authorize!(:write_feedback_target, feedback_target) do
      define_breadcrumbs
      add_breadcrumb  t('Edit')
    end
  end

  def create
    @feedback_target =  current_user.feedback_targets.build(feedback_target_params)
    if @feedback_target.save
      flash[:notice] = translate('User application created!')
      redirect_to :action => :index
    else
      render :new
    end
  end

  def update
    authorize!(:write_feedback_target, feedback_target) do
      if feedback_target.update_attributes(feedback_target_params)
          flash[:notice] = translate('User application changed successfully!')
          redirect_to :action => :index
      else
        render :edit
      end
    end
  end

  def search_for_members
    @users = feedback_target.list_members_candidates(params[:username])
    render json: @users, :root => false, :each_serializer => UserAutocompleteSerializer
  end

  def remove_member
    @feedback_target = feedback_target
    authorize!(:admin_team_members, @feedback_target) do
      respond_to do |format|
       if @feedback_target.remove_member params[:member_id]
         format.html { redirect_to @feedback_target, notice: 'Members successfully removed.' }
         format.json { render json: @feedback_target.members, :root => false, :each_serializer => UserAutocompleteSerializer }
         # added:
         format.js   { render action: 'members_list' }
       else
         #byebug
         format.html { render action: 'edit', :locals => {:feedback_target => feedback_target} }
         format.json { render json: @feedback_target.errors, status: :unprocessable_entity }
         # added:
         format.js   { render json: @feedback_target.errors, status: :unprocessable_entity }
       end
      end
    end
  end

  def add_members
    @feedback_target = feedback_target
    authorize!(:admin_team_members, @feedback_target) do
      respond_to do |format|
       if @feedback_target.include_members params[:team_members_ids]
         format.html { render action: 'edit', notice: 'Members successfully added.' }
         format.json { render json: @feedback_target.members, :root => false, :each_serializer => UserAutocompleteSerializer }
         # added:
         format.js   do
           render action: 'members_list'
         end
       else
         format.html { render action: 'edit' }
         format.json { render json: @feedback_target.errors, status: :unprocessable_entity }
         # added:
         format.js   { render json: @feedback_target.errors, status: :unprocessable_entity }
       end
      end
    end
  end

  def destroy
    authorize!(:destroy_feedback_target, feedback_target) do
      feedback_target.destroy
      flash[:notice] = translate('User application removed successfully!')
      redirect_to :action => :index
    end
  end


private
  def feedback_target
    @feedback_target ||= FeedbackTarget.all_targets_for_user(current_user).find(id_param)
  end

  def define_breadcrumbs
    add_breadcrumb  feedback_target.name, feedback_target
  end

  def id_param
    params[:id]
  end

  def feedback_target_params
    params.require(:feedback_target).permit :name
    # if current_user.nil? # Guest
    #   # Remove all keys from params[:user] except :name, :email, :password, and :password_confirmation
    #   params.require(:feedback_target).permit :name
    # elsif current_user.has_role :admin
    #   params.require(:feedback_target).permit! # Allow all user parameters
    # elsif current_user.has_role :user
    #   params.require(:feedback_target).permit :name
    # end
  end
end

app/helpers/feedback_targets_helper.rb
module FeedbackTargetsHelper
  def format_member_for_list(member)
    return "" if member.nil?
    return "#{member.username} (#{member.email})"
  end

end

app/views/feedback_targets/_feedback_js_code.html.erb
    $(document).ready(function() {
      Feedback(
              {
                  label: "Reportar",
                  header: "Registro de ocorrência",
                  url: "<%= app_base_url %>/api/v1/feedbacks?access_token=<%= feedback_target.authentication_token %>",
                  nextLabel: "Continuar",
                  reviewLabel: "Revisar",
                  sendLabel:  "Enviar",
                  closeLabel: "Fechar",
                  highlightBlackoutHelp: "Você pode destacar informações úteis ou ocultar informações sensíveis.",
                  blackoutButtonLabel: "Ocultar",
                  highlightButtonLabel: "Destacar",
                  messageSuccess: "O seu relato foi enviado com sucesso!",
                  messageError: "Houve um erro ao enviar o relato...",
                  pages: [
                          new window.Feedback.Form([
                                  {
                                      type: "select",
                                      name: "tipo_relato",
                                      label: "Tipo de Relato",
                                      options: ["Sugestão", "Erro"],
                                      required: true
                                  },
                                  {
                                          type: "select",
                                          name: "severidade",
                                          label: "Severidade",
                                          options: ["Leve", "Média", "Crítica"],
                                          required: true
                                  },
                                  {
                                      type: "starrating",
                                      name: "starrating",
                                      label: "Avalie",
                                      options: ["Insatisfeito", "2", "3", "4", "Muito Satisfeito"],
                                      required: true
                                  },
                                 {
                                      type: "textarea",
                                      name: "relato",
                                      label: "Relato",
                                      required: true
                                  },
                                  {
                                      type: "hidden",
                                      name: "situacao",
                                      value: "aberto",
                                      review: false
                                  }
                                  ]
                          ),
                          new window.Feedback.Screenshot(),
                          new window.Feedback.Review()
                  ]
               });
    });

app/views/feedback_targets/_feedback_js_include.html.erb
<%=h "<link href='#{app_base_url}/assets/feedback.css' media='all' rel='stylesheet'>" %>
<%=h "<script src='#{app_base_url}/assets/feedback_client.js'></script>" %>

app/views/feedback_targets/_feedback_js_viewer.html.erb
<%= content_for :head do %>

<% end %>
<hr/>
  <p>Incluir o código abaixo nas páginas da aplicação <strong><%= @feedback_target.name %></strong></p>
  <pre class="preview_source">
    <code class="xhtml">
<%= render_js_include() %>
&lt;script type=text/javascript&gt;
<%= render_code(@feedback_target) %>
&lt;/script&gt;</code>
    <!-- <code class="language-javascript"><%#= render_code(@feedback_target) %></code> -->
  </pre>

app/views/feedback_targets/_members_edit.html.erb
<%= bootstrap_form_for(@feedback_target, url: url_for(add_members_for_feedback_target_path(@feedback_target)),method: 'post', remote: true, :html => {:id => 'form_members'}) do |f| %>
<%= f.alert_message t('alert_errors') %>
  <div class="row">
    <div class="col-lg-6">
      <label for='team_members_ids'>Adicionar Usuários</label>
        <%= text_field_tag :team_members_ids, "",
        data: {
          placeholder: "Selecione os membros de sua equipe:",
          #@feedback_target.team_members.to_json :each_serializer UserAutocompleteSerializer
          saved: '[]',
          url: members_for_feedback_target_path},
          class: "autocomplete",
            style: "width:100%"
            %>

    </div>
    <div class="col-lg-6">
      <h6>Usuários com acesso</h6>
      <div id='members_list'>
      <%= render :partial => 'members_list', :locals => {:members => @feedback_target.members} %>
      </div>
    </div>
  </div>

  <h6>Convidar</h6>
  <p>Em breve será possível enviar convite por email!</p>
<% end %>
<% content_for :body_end  do%>
  <script type="text/javascript">
  function configurarAutocomplete() {
    // $('#invite_members_emails').each(function(){
    //   //tags: true,
    //   //tokenSeparators: [',', ' '],
    // });
    $('#team_members_ids').each(function() {
      var url = $(this).data('url');
      var placeholder = $(this).data('placeholder');
      var saved = <%= raw @feedback_target.members_usernames.as_json %> ;
      $(this).select2({
        minimumInputLength: 2,
        multiple: true,
        placeholder : placeholder,
        allowClear: true,
        ajax: {
          url: url,
          dataType: 'json',
          quietMillis: 500,
          data: function (term) {
            return {
              username: term
            };
          },
          results: function (data) {
            return {results: data};
          }
        },

        formatResult: function (item, page) {
          return item.username + '(' + item.email + ')';
        },

        formatSelection: function (item, page) {
          return item.username ;
        },

        initSelection : function (element, callback) {
          if (saved) {
            callback(saved);
          }
        }

      }).on('change', function() {
                        if($(this).val() !== '') {
                          $('#form_members').submit();
                      }
      });
    });
  }
  jQuery(document).on('ready page:load', configurarAutocomplete);
  </script>
<% end %>

app/views/feedback_targets/_members_list.html.erb
  <ul class="no-bullet users_list">
    <% members.each do |m| %>
      <li><%= format_member_for_list(m)%>
        <%= link_to t('remove_member'), url_for(remove_member_for_feedback_target_path(:member_id => m.id)), :remote => true, :method => :delete%></li>
    <% end %>
  </ul>

app/views/feedback_targets/_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
      <h3 class="panel-title"><%= t('User Applications') %></h3>
  </div>
  <div class="panel-body">
    <% if @feedback_targets.empty? %>

      <p> <%= translate("No application registered yet") %></p>

    <% else  %>

      <div class="table-responsive">
          <table class="table table-bordered table-hover table-striped">
              <thead>
                  <tr>
                    <th><%= translate('Name') %></th>
                    <th><%= translate('Token') %></th>
                    <th></th>
                  </tr>
              </thead>
              <tbody>
                 <% @feedback_targets.each do  |feedback_target | %>
                    <tr>
                      <td><%= link_to feedback_target.name, feedback_target_path(feedback_target) %></td>
                      <td><%= feedback_target.authentication_token %></td>

                      <td><%#= link_to(
                          content_tag(:span, pad(translate('Feedbacks')) + " ", :class => 'fa fa-comment-o'),
                          feedback_target_feedbacks_path(feedback_target))%></td>
                    </tr>
                 <% end %>
              </tbody>
          </table>
      </div>
      <% end %>
      <div class="text-right">
          <%= link_to translate('All'), feedback_targets_path%>
      </div>
  </div>
</div>

app/views/feedback_targets/create.html.erb
<h1>FeedbackTargets#create</h1>
<p>Find me in app/views/feedback_targets/create.html.erb</p>

app/views/feedback_targets/destroy.html.erb
<h1>FeedbackTargets#destroy</h1>
<p>Find me in app/views/feedback_targets/destroy.html.erb</p>

app/views/feedback_targets/edit.html.erb
<h1 class="page-header"><%= translate('feedback_target.page_title.edit') %></h1>


<%= bootstrap_form_for @feedback_target, :role =>  'form' do |f| %>
	<%= f.text_field 'name', :autofocus => 'true', label: t('Name') %>
	<%= f.submit t("Submit") %>
<% end %>


<div id='member_edit_container'>
<%= render :partial => 'members_edit' if  current_user_can?(:admin_team_members, @feedback_target)%>
</div>

app/views/feedback_targets/edit.js.erb
$('#member_edit_container').html('<%= escape_javascript(render :partial => 'members_edit'})%>');

app/views/feedback_targets/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            <%= translate('My applications') %>
        </h1>
        <!-- <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> Dashboard
            </li>
        </ol> -->
    </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
      <h3 class="panel-title"><%= t('User Applications') %></h3>
  </div>
  <div class="panel-body">
    <% if @feedback_targets.empty? %>

      <p> <%= translate("No application registered yet") %></p>

      <div class=''>
        <%= link_to new_feedback_target_path, :class => 'btn btn-primary' do %>
          <i class="fa fa-desktop"></i> <%= t('Create new application') %>
        <% end %>
      </div>

    <% else  %>
    <div class="text-left">
        <%= link_to new_feedback_target_path, :class => 'btn btn-primary' do %>
        <i class="fa fa-desktop"></i> <%= t('Create new application') %>
        <% end %>
    </div>
    <hr />
      <div class="table-responsive">
          <table id="targets_list" class="table table-bordered table-hover table-striped">
              <thead>
                  <tr>
                    <th><%= translate('Name') %></th>
                    <th><%= translate('Actions') %></th>
                  </tr>
              </thead>
              <tbody>
                 <% @feedback_targets.each do  |feedback_target | %>
                    <tr>
                      <td><%= link_to feedback_target.name, feedback_target_path(feedback_target) %></td>
                      <td>
                        <%= render_action 'edit', feedback_target if current_user_can?(:write_feedback_target, feedback_target) %>
                        <%= render_action 'destroy', feedback_target if current_user_can?(:destroy_feedback_target, feedback_target) %>
                        <%= render_action 'forms', feedback_target if current_user_can?(:write_feedback_target, feedback_target) %>
                      </td>
                    </tr>
                 <% end %>
              </tbody>
          </table>
      </div>
      <% end %>
  </div>
</div>

app/views/feedback_targets/members_list.js.erb
$('#members_list').html('<%= escape_javascript(render :partial => 'members_list', :locals => {members:  @feedback_target.members})%>');
$('#team_members_ids').val(null).trigger('change');

app/views/feedback_targets/show.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            <%= @feedback_target.name %>
        </h1>
        <!-- <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> Dashboard
            </li>
        </ol> -->
    </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
      <h3 class="panel-title"><%= t('Application Info') %></h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-8">
        <%= bootstrap_form_tag do |f| %>
        <div class="form-group">
          <label>Nome:</label> <%= @feedback_target.name %>
        </div>
        <div class="form-group">
           <%= link_to_if(
            @feedback_target.owner.id.eql?(current_user.id),
            content_tag(:span, pad(translate('Edit')), class: 'fa fa-edit'),
            edit_feedback_target_path(@feedback_target), :class=> 'action') do
            end
            %>
        </div>
        <% end %>
      </div>

    </div>

  </div>
</div>

<%= render partial: 'feedback_forms/index/panel' %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t('feedback_target.panel_title.members') %></h3>
  </div>
  <div class="panel-body">
    <%= render :partial => 'members_edit' if  current_user_can?(:admin_team_members, @feedback_target)%>
  </div>
</div>

<!-- <div class="panel panel-default">
  <div class="panel-heading">
      <h3 class="panel-title"><%= t('Feedback Javascript Source') %></h3>
  </div>
  <div class="panel-body"> -->
    <%#= render :partial => 'feedback_js_viewer' %>
  <!-- </div>
</div> -->



<%#= link_to t('view feedbacks'), feedback_target_feedbacks_path(@feedback_target) %>

app/views/feedback_targets/update.html.erb
<h1><%= translate('My applications') %></h1>

<%= form_for @feedback_target do |f| %>
  <%= f.text 'name' %>
  <%= f.submit translate('Submit'), :class => 'button small alternative' %>
<% end %>