config/routes.rb
 Rails.application.routes.draw do

  devise_for :expresso_user, :registered_user, :ldap_users, skip: [ :sessions ]

  devise_scope :expresso_user do
    root to: "sessions#new", :as => 'expresso_user_root'
    get 'sign_in' => 'sessions#new', :as => :new_session_expresso_user
    match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    get '/auth/failure', to: 'sessions#omniauth_failure'
    get 'sign_out' => 'sessions#destroy'
  end

  devise_scope :ldap_user do
    root to: "sessions#new"
    delete 'sign_out' => 'sessions#destroy'
   end

  devise_scope :registered_user do
    root to: "sessions#new", :as => 'registered_user_root'
    get 'sign_in' => 'sessions#new', :as => :new_session
    post 'sign_in' => 'sessions#create', :as => :create_session
    delete 'sign_out' => 'sessions#destroy', :as => :destroy_session
  end

  get 'dashboard' => "dashboard#index"

  get 'widget/:token' => 'feedback_forms#code'

  get 'protected' => 'protected#index'

  get 'proxy' => 'proxy#index'

  resources  :feedback_targets do
    member do
     get 'search_for_members' => 'feedback_targets#search_for_members', as: 'members_for'
     post 'add_members' => 'feedback_targets#add_members', as: 'add_members_for'
     delete 'remove_member' => 'feedback_targets#remove_member', as: 'remove_member_for'
    end
    resources :feedbacks do

    end
    resources :feedback_forms do
      member do
        delete 'destroy_attribute' => 'feedback_forms#destroy_attribute'
        get 'new_attribute' => 'feedback_forms#new_attribute'
      end
      resources :feedbacks do
        member do
          delete 'destroy_comment' => 'feedbacks#destroy_comment'
          post 'add_comment' => 'feedbacks#add_comment'
          post 'archive' => 'feedbacks#archive'
          post 'unarchive' => 'feedbacks#unarchive'
          get 'comments' => 'feedbacks#comments'
          put 'fire_event'=> 'feedbacks#fire_event'
          get 'show_detail'=> 'feedbacks#show_detail'
        end
      end
    end
  end

  get '/users/autocomplete', to: 'users#autocomplete', as: 'autocomplete_user'

  get '/user_applications', to: redirect('/feedback_targets')
  get '/user_applications/:feedback_target_id', to: redirect  { |path_params, req| "/feedback_targets/#{path_params[:feedback_target_id]}" }

  mount FeedbackServerAPI => '/api/'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar_login.html.erb
<!--
<ul class="nav pull-right">
  <li class="dropdown" id="menuLogin">
    <a class="dropdown-toggle" href="#" data-toggle="dropdown" id="navLogin">Login</a>
    <div class="dropdown-menu" style="padding:17px;">
      <form class="form" id="formLogin">
        <input name="username" id="username" type="text" placeholder="Username">
        <input name="password" id="password" type="password" placeholder="Password"><br>
        <button type="button" id="btnLogin" class="btn">Login</button>
      </form>
    </div>
  </li>
</ul> -->
<% if current_user.present? %>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.username %><b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li>
        <%= link_to  dashboard_path   do%>
          <i class="fa fa-fw fa-dashboard"></i> <%= t("Dashboard_Reduced") %>
        <% end %>

        </li>
        <li>
          <%= link_to  "/feedback_targets/new"  do%>
            <i class="fa fa-fw fa-plus"></i><%= t("Application") %>
          <% end %>
        </li>
        <li class='disabled'>
            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
        </li>
        <li class='disabled'>
            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
        </li>
        <li class='disabled'>
            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
        </li>
        <li class="divider"></li>
        <li>
        <%= link_to destroy_session_path, :method => :delete do %>
              <i class="fa fa-fw fa-power-off"></i><%= t 'Logout' %>
          <% end %>
        </li>
    </ul>
</li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 4 %>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name"><%= link_to translate('FeedbackSERPRO'), root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
<div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
        <li class="active">
            <%= link_to  dashboard_path   do%>
              <i class="fa fa-fw fa-dashboard"></i> <%= t("Dashboard") %>
            <% end %>
        </li>
        <li>
          <%= link_to  feedback_targets_path   do%>
            <i class="fa fa-fw fa-desktop"></i> <%= t("Applications") %>
          <% end %>
        </li>
        <li>
          <%= link_to  feedback_targets_path   do%>
            <i class="fa fa-fw fa-wrench"></i> <%= t("Configurations") %>
          <% end %>
        </li>
        <li>
          <%= link_to  feedback_targets_path   do%>
            <i class="fa fa-fw fa-file"></i> <%= t("Templates") %>
          <% end %>
        </li>
      
        <!-- <li>
            <a href="charts.html"><i class="fa fa-fw fa-bar-chart-o"></i> Charts</a>
        </li>
        <li>
            <a href="tables.html"><i class="fa fa-fw fa-table"></i> Tables</a>
        </li>

        <li>
            <a href="bootstrap-elements.html"><i class="fa fa-fw fa-desktop"></i> Bootstrap Elements</a>
        </li>
        <li>
            <a href="bootstrap-grid.html"><i class="fa fa-fw fa-wrench"></i> Bootstrap Grid</a>
        </li>
        <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Dropdown <i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="demo" class="collapse">
                <li>
                    <a href="#">Dropdown Item</a>
                </li>
                <li>
                    <a href="#">Dropdown Item</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="blank-page.html"><i class="fa fa-fw fa-file"></i> Blank Page</a>
        </li>
        <li>
            <a href="index-rtl.html"><i class="fa fa-fw fa-dashboard"></i> RTL Dashboard</a>
        </li> -->
    </ul>
</div>
<!-- /.navbar-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Feedback.SERPRO" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "App Rails Jruby" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= yield :head%>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" id="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <%= yield :body_end %>
  </body>
</html>

app/views/layouts/bootstrap_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Feedback.SERPRO" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <script src="/highlight/highlight.pack.js"></script>

    <link href="/highlight/styles/atelier-lakeside.light.css" rel="stylesheet" />

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <%= yield :head %>
    <style type="text/css">
    .breadcrumb > li + li:before {
      display:none
    }
    </style>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Feedback.SERPRO</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to translate("Home"), "/"  %></li>
            <li><%= link_to translate("Applications"), "/feedback_targets"  %></li>
            <li><%#= link_to translate("Last Feedbacks"), "/last_feedbacks"  %></li>
          </ul>
          <%= render :partial => "/layouts/navbar_login" %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <%= render_breadcrumbs("/") %>
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!--<div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div> <!--/.well
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <!--<p>&copy; Feedback.SERPRO 2014</p>-->
      </footer>

    </div> <!-- /container -->
  <%= yield :body_end %>
  </body>
</html>

app/views/layouts/errors.html.erb
<h1>OPs</h1>
<p>Acontenceu algo de errado !!!</p>
<hr />
<%= yield %>

app/views/layouts/layout2.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Feedback.SERPRO" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "layout2", :media => "all" %>

    <script src="/highlight/highlight.pack.js"></script>

    <link href="/highlight/styles/atelier-lakeside.light.css" rel="stylesheet" />

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <!-- Favicon icon http://www.iconarchive.com/show/origami-colored-pencil-icons-by-double-j-design/yellow-balloon-plus-icon.html -->
    <link rel="icon"  type="image/png" href="/images/black-balloon-plus-icon.png">

    <%= yield :head %>
    <style type="text/css">
    .breadcrumb > li + li:before {
      display:none
    }
    </style>
    <!-- application.js should be here while using turbolinks, otherwise some jquery plugins
           like select 2 does not work
            Information source: https://github.com/select2/select2/issues/1582
            -->
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <%= wrapper_div do %>

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Fechar menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="toggleMenu navbar-brand" href="javascript:;" id=""><i class='fa fa-bars'>&nbsp;</i></a>
                <%= link_to 'Feedback.Serpro', url_for(dashboard_path), :class => "navbar-brand" %>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-footer">
                            <a href="#">Read All New Messages</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>
                <%= render :partial => "/layouts/navbar_login" %>

            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <%= render :partial => 'layouts/sidebar' %>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">
                <%= bootstrap_flash %>
                <%= render_breadcrumbs %>
                <%= yield %>

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    <% end %>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <!--script src="js/jquery.js"></script-->

    <!-- Bootstrap Core JavaScript -->
    <!--script src="js/bootstrap.min.js"></script-->

    <!-- Morris Charts JavaScript -->
    <!--script src="js/plugins/morris/raphael.min.js"></script>
    <script src="js/plugins/morris/morris.min.js"></script>
    <script src="js/plugins/morris/morris-data.js"></script-->

    <%= yield :body_end %>
    <%= serpro_logo %>
</body>

</html>

app/views/layouts/login_page.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Feedback.SERPRO" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "login", :media => 'all' %>


    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "login" %>

  </head>
  <body>
    <div class="container">
<%= yield %>
    </div>
</body>

</html>